version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: voyage-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped
    networks:
      - voyage-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: voyage-frontend
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    restart: unless-stopped
    networks:
      - voyage-network
    depends_on:
      - server

networks:
  voyage-network:
    driver: bridge
